// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2UYnydcGcNXCEsy7rRGj5iuy52J87js',
    appId: '1:343920377818:web:52f289ede28264d3300ae3',
    messagingSenderId: '343920377818',
    projectId: 'talksy-app-a4a48',
    authDomain: 'talksy-app-a4a48.firebaseapp.com',
    storageBucket: 'talksy-app-a4a48.firebasestorage.app',
    measurementId: 'G-B3P6X40QXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5PxpGc3C4sNCtWnEU7DLu2vW8dC8v9Cc',
    appId: '1:343920377818:android:b29765e49fb5faf8300ae3',
    messagingSenderId: '343920377818',
    projectId: 'talksy-app-a4a48',
    storageBucket: 'talksy-app-a4a48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAez3kUFz9WYxQnz-ZwKri8NpButoMrsac',
    appId: '1:343920377818:ios:24f2e3818c3055c6300ae3',
    messagingSenderId: '343920377818',
    projectId: 'talksy-app-a4a48',
    storageBucket: 'talksy-app-a4a48.firebasestorage.app',
    iosBundleId: 'com.example.talksyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAez3kUFz9WYxQnz-ZwKri8NpButoMrsac',
    appId: '1:343920377818:ios:24f2e3818c3055c6300ae3',
    messagingSenderId: '343920377818',
    projectId: 'talksy-app-a4a48',
    storageBucket: 'talksy-app-a4a48.firebasestorage.app',
    iosBundleId: 'com.example.talksyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2UYnydcGcNXCEsy7rRGj5iuy52J87js',
    appId: '1:343920377818:web:ca623a7526e94510300ae3',
    messagingSenderId: '343920377818',
    projectId: 'talksy-app-a4a48',
    authDomain: 'talksy-app-a4a48.firebaseapp.com',
    storageBucket: 'talksy-app-a4a48.firebasestorage.app',
    measurementId: 'G-008CRQJGQR',
  );
}
